# Generated by Django 4.0.1 on 2022-01-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vaga_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='horaDeSaida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
