# Generated by Django 4.0.1 on 2022-01-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ticket_horadesaida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
