# Generated by Django 4.0.1 on 2022-01-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ticket_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='ocupado',
        ),
    ]
