# Generated by Django 4.0.1 on 2022-01-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_vaga_ocupado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='horaDeEntrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
