# Generated by Django 4.0.1 on 2022-01-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_ticket_horadeentrada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'permissions': (('carro_perm', 'Pode maniuplar a entidade carro'),)},
        ),
        migrations.AlterModelOptions(
            name='vaga',
            options={'permissions': (('vaga_perm', 'Pode maniuplar a entidade vaga'),)},
        ),
    ]
